/**
 * Token build for @brand/tokens.
 *
 * Source of truth: src/**\/*.json  (core -> semantic -> brand -> theme)
 * Output:          generated/{css,less,scss,ts,json}
 *
 * The CSS output is a single file with one selector block per brand/theme
 * combination, so a running app can switch brand or colour-scheme at runtime
 * by toggling `data-brand` / `data-theme` on <html> — no rebuild required.
 *
 * When the real Figma variables are available, replace the files under src/
 * (keep the same token paths) and re-run `nx build tokens`.
 */
import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'generated');
const PARTIALS = path.join(OUT, '_partials');

const PREFIX = 'ds';
const DEFAULT_BRAND = 'konica';
const BRANDS = ['konica', 'aurora'];
const THEMES = ['light', 'dark'];

/** vars-only CSS body (no selector wrapper) so the concat step can place it. */
StyleDictionary.registerFormat({
  name: 'css/vars-body',
  format: ({ dictionary }) =>
    dictionary.allTokens
      .map((t) => `  --${PREFIX}-${t.name}: ${t.value};`)
      .join('\n'),
});

function sourcesFor(brand, theme) {
  const files = [
    `${SRC}/core/**/*.json`,
    `${SRC}/semantic/**/*.json`,
    `${SRC}/brand/${brand}.json`,
  ];
  if (theme === 'dark') files.push(`${SRC}/theme/dark.json`);
  return files;
}

function partialPath(brand, theme) {
  return path.join(PARTIALS, `${brand}.${theme}.css`);
}

async function buildPartials() {
  for (const brand of BRANDS) {
    for (const theme of THEMES) {
      const sd = new StyleDictionary({
        source: sourcesFor(brand, theme),
        platforms: {
          css: {
            transformGroup: 'css',
            buildPath: PARTIALS + '/',
            files: [
              {
                destination: `${brand}.${theme}.css`,
                format: 'css/vars-body',
              },
            ],
          },
        },
        log: { warnings: 'disabled', verbosity: 'silent' },
      });
      await sd.buildAllPlatforms();
    }
  }
}

async function buildAncillary() {
  // Less + SCSS + JS + JSON from the default brand, light theme.
  const sd = new StyleDictionary({
    source: sourcesFor(DEFAULT_BRAND, 'light'),
    platforms: {
      less: {
        transformGroup: 'less',
        prefix: PREFIX,
        buildPath: OUT + '/less/',
        files: [{ destination: '_tokens.less', format: 'less/variables' }],
      },
      scss: {
        transformGroup: 'scss',
        prefix: PREFIX,
        buildPath: OUT + '/scss/',
        files: [{ destination: '_tokens.scss', format: 'scss/variables' }],
      },
      js: {
        transformGroup: 'js',
        buildPath: OUT + '/ts/',
        files: [
          { destination: 'tokens.mjs', format: 'javascript/es6' },
          { destination: 'tokens.d.ts', format: 'typescript/es6-declarations' },
        ],
      },
      json: {
        transformGroup: 'js',
        buildPath: OUT + '/json/',
        files: [{ destination: 'tokens.json', format: 'json/nested' }],
      },
    },
    log: { warnings: 'disabled', verbosity: 'default' },
  });
  await sd.buildAllPlatforms();

  // Dark values of the default brand — consumed by the ng-zorro dark compile.
  const dark = new StyleDictionary({
    source: sourcesFor(DEFAULT_BRAND, 'dark'),
    platforms: {
      json: {
        transformGroup: 'js',
        buildPath: OUT + '/json/',
        files: [{ destination: 'tokens.dark.json', format: 'json/nested' }],
      },
    },
    log: { warnings: 'disabled', verbosity: 'silent' },
  });
  await dark.buildAllPlatforms();
}

function selectorsFor(brand, theme) {
  const isDefault = brand === DEFAULT_BRAND;
  if (theme === 'light') {
    return isDefault ? [':root'] : [`[data-brand="${brand}"]`];
  }
  // dark
  return isDefault
    ? [':root[data-theme="dark"]']
    : [`[data-brand="${brand}"][data-theme="dark"]`];
}

async function concatCss() {
  const header =
    `/* Generated by style-dictionary.config.mjs — do not edit by hand. */\n` +
    `/* Runtime theming: set data-brand="konica|aurora" and data-theme="light|dark" on <html>. */\n\n`;

  const blocks = [];
  for (const theme of THEMES) {
    for (const brand of BRANDS) {
      const body = await fs.readFile(partialPath(brand, theme), 'utf8');
      for (const sel of selectorsFor(brand, theme)) {
        blocks.push(`${sel} {\n${body}\n}`);
      }
    }
  }

  // OS-level dark before any explicit data-theme is applied (pre-hydration /
  // no BrandThemeService). Scoped to `:not([data-theme])` so it never fights an
  // explicit choice, and kept per-brand so a persisted brand still gets its own
  // dark palette on first paint.
  const mediaBlocks = [];
  for (const brand of BRANDS) {
    const body = await fs.readFile(partialPath(brand, 'dark'), 'utf8');
    const sel =
      brand === DEFAULT_BRAND
        ? ':root:not([data-theme])'
        : `[data-brand="${brand}"]:not([data-theme])`;
    mediaBlocks.push(`  ${sel} {\n${body}\n  }`);
  }
  blocks.push(
    `@media (prefers-color-scheme: dark) {\n${mediaBlocks.join('\n\n')}\n}`,
  );

  await fs.mkdir(path.join(OUT, 'css'), { recursive: true });
  await fs.writeFile(
    path.join(OUT, 'css', 'tokens.css'),
    header + blocks.join('\n\n') + '\n',
    'utf8',
  );
  await fs.rm(PARTIALS, { recursive: true, force: true });
}

async function main() {
  await fs.rm(OUT, { recursive: true, force: true });
  await buildPartials();
  await buildAncillary();
  await concatCss();
  console.log('\n✔ tokens built ->', path.relative(process.cwd(), OUT));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
