/**
 * `@brand/tokens` — design-token metadata and helpers.
 *
 * Token *values* are generated by `nx build tokens` (Style Dictionary) into
 * `libs/tokens/generated/`:
 *   - `css/tokens.css`     runtime CSS custom properties for every brand + theme
 *   - `less/_tokens.less`  Less variables consumed by the ng-zorro theme map
 *   - `scss/_tokens.scss`  Sass variables
 *   - `ts/tokens.mjs`      typed token map for non-CSS consumers
 *   - `json/tokens.json`   flat reference (docs / Figma round-trip)
 *
 * Applications import `@brand/tokens/css` once at bootstrap; components should
 * only ever read `var(--ds-*)`, never hard-coded values.
 */
export type Brand = 'brand-1' | 'brand-2' | 'brand-3';
export type ColorScheme = 'light' | 'dark';

export const BRANDS: readonly Brand[] = ['brand-1', 'brand-2', 'brand-3'] as const;
export const COLOR_SCHEMES: readonly ColorScheme[] = ['light', 'dark'] as const;

/** CSS custom-property prefix shared by every generated token. */
export const TOKEN_PREFIX = 'ds' as const;

/**
 * Build a `var(--ds-<name>)` reference, optionally with a fallback.
 * @example cssVar('color-action-primary') // 'var(--ds-color-action-primary)'
 */
export function cssVar(name: string, fallback?: string): string {
  const suffix = fallback ? `, ${fallback}` : '';
  return `var(--${TOKEN_PREFIX}-${name}${suffix})`;
}
